### ISSUE TITLE
Zoneninfos ffmd sind unvollständig

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/ffmd_bind9#6]
- [x] gw01.babel → fda9:26e:5805:bab1:aaaa::1
- [x] gw02.babel → fda9:26e:5805:bab1:aaaa::2
- [x] gw1 → fda9:26e:5805::9
- [x] gw2 → fda9:26e:5805::2
- [x] web → fda9:26e:5805:bab1:aaaa::0
- [x] web1 → fda9:26e:5805::10

**Comment by penguineer** [comment]
gw01.babel →  fda9:26e:5805:bab1:aaaa::1
gw02.babel →  fda9:26e:5805:bab1:aaaa::2

**Comment by penguineer** [comment]
web könnte  fda9:26e:5805:bab1:aaaa::0 erhalten

**Comment by penguineer** [comment]
gw2 →  fda9:26e:5805::2

**Comment by 24367dfa** [comment]
haben wir schon eine IP für gw1?

**Comment by penguineer** [comment]
> haben wir schon eine IP für gw1?

Ich habe gerade oben eingetragen, was ich in den Systemen abgelesen habe.
Außerdem ist bei der Gelegenheit web1 noch hinzugekommen.

**Comment by penguineer** [comment]
gw02.babel ist ein wenig wacklig. Der Server ist seit Juli offline und wir erreichen den Betreiber nicht.

Der mittelfristige Plan ist, das gw2 zum gw02.babel umzuwidmen, aber dafür müssen wir erst die Struktur der Ausleitung anpassen und das gw1 fixen. Eventuell kommt vorher auch noch eine Firmware-Anpassung.

Alles leider etwas komplexer.

Grundsätzlich könnten wir diese Adressen IMHO so aber annehmen.
