### ISSUE TITLE
Serial Number (Commit + Tags) automatisch anlegen

### ISSUE THREAD

**Issue by penguineer** [FreifunkMD/ffmd_bind9#8]
Bei Pushes auf den Branch sollen die Serial Number der Zone und ein entsprechenes Tag über eine GitHub Action automatisch erstellt werden.

**Comment by penguineer** [comment]
Es gibt mit https://github.com/FreifunkMD/md.freifunk.net-bind9/pull/13 bereits eine Lösung für md.freifunk.net, die wir aber noch nicht getestet haben.

**Comment by 24367dfa** [comment]
soll ichs einfach duplizieren, oder lieber schauen, dass ichs als eigene action umbaue?

**Comment by penguineer** [comment]
> soll ichs einfach duplizieren, oder lieber schauen, dass ichs als eigene action umbaue?

Ich würde die Action im anderen Repo gern  erstmal nochmal anfassen (sitze aber gerade an Infrastruktur).

Vorschlag: Wir machen erstmal ein Test-Repo, in  dem wir rumspielen, bis alles geht, erstellen dann ein allgemeines Repo für die Actions und bauen das anschließend hier ein.
